
version: '2'
services:
  glide:
    image: eu.gcr.io/altipla-tools/glide:latest
    build:
      context: containers/glide

  go:
    image: eu.gcr.io/altipla-tools/go:latest
    build:
      context: containers/go

  node:
    image: eu.gcr.io/altipla-tools/node:latest
    build:
      context: containers/node

  protoc:
    image: eu.gcr.io/altipla-tools/protoc:latest
    build:
      context: containers/protoc

  rambler:
    image: eu.gcr.io/altipla-tools/rambler:latest
    build:
      context: containers/rambler

  gcloud:
    image: eu.gcr.io/altipla-tools/gcloud:latest
    build:
      context: containers/gcloud

  gulp:
    image: eu.gcr.io/altipla-tools/gulp:latest
    build:
      context: containers/gulp

  sass-lint:
    image: eu.gcr.io/altipla-tools/sass-lint:latest
    build:
      context: containers/sass-lint

  phpmyadmin:
    image: eu.gcr.io/altipla-tools/phpmyadmin:latest
    build:
      context: containers/phpmyadmin

  mysql:
    image: eu.gcr.io/altipla-tools/mysql:latest
    build:
      context: containers/mysql

  dev-go:
    image: eu.gcr.io/altipla-tools/dev-go:latest
    build:
      context: containers/dev-go

  king:
    image: eu.gcr.io/altipla-tools/king:latest
    build:
      context: containers/king

  juice:
    image: eu.gcr.io/altipla-tools/juice:latest
    build:
      context: containers/juice

  dev-gulp:
    image: eu.gcr.io/altipla-tools/dev-gulp:latest
    build:
      context: containers/dev-gulp

  baster:
    image: eu.gcr.io/altipla-tools/baster:latest
    build:
      context: containers/baster

  cloudsqlproxy:
    image: eu.gcr.io/altipla-tools/cloudsqlproxy:latest
    build:
      context: containers/cloudsqlproxy
